### ISSUE TITLE
Nutzung als Swarm / Kubernetes Service

### ISSUE THREAD

**Issue by kremer-io** [schul-cloud/libreoffice-online-builder#1]
Wie kann der Service in Swarm oder Kubernetes genutzt werden? Insb. der Umstand, dass sich in einen vorhandenen Container eingeloggt und dann Dateien verändert werden müssen, ist im Bereich von Services eher schwierig. Gibt es die Möglichkeit SSL im Container zu deaktivieren und dies einen Reverse Proxy übernehmen zu lassen?

**Comment by MatthiasWiesner** [comment]
SSL kann auf dieselbe Art abgestellt werden wie [in diesem Issue](2) beschrieben wird.
Hatte zum Test einen Nginx vorgeschaltet - ohne SSL Terminierung. Ein Request hatte jedoch sehr lange gebraucht. Das Thema Reverse Proxy muss noch detaillierter untersucht werden.
